### ISSUE TITLE
Alias?

### ISSUE THREAD

**Issue by raiph** [Scimon/Timer-Breakable#1]
Hi scimon,

I haven't yet used this module, and am not concerned about it in particular, and if you don't feel it worth the hassle of doing anything about this "issue", then that's perfectly cromulent, but I was reading the  latest advent...

jjatria has [a good point](https://raku-advent.blog/2020/12/12/day-12-that-raku-feeling/#footnotes).

In general the Raku packaging approach in regard to package names/versions/evolution is pretty great.

But I don't know about long term (5-10 year) aliasing/renaming/deprecation etc. related to a package name. If there are already mechanisms for that, then great, and perhaps the thing to do is either apply that if you feel like it or just close this issue because it's not a big deal.

But If aliasing/renaming/deprecation has *not* been well addressed, that would seem like a fly in what is otherwise Raku's pretty wonderful packaging system ointment, at least as far as identities are concerned.

And if an alias/rename/deprecation is fraught, then perhaps this module, would be a great choice to lead the way in smoothing out the wrinkles in 2021-2025 or thereabouts?

If you don't think it's worth worrying about, or at least doing so for this package, that's entirely OK and I'll be happy if one of us closes it, but I wanted to leave this thought somewhere.

**Comment by Scimon** [comment]
Is this renaming it to Timer::Callable?
The reason for calling it Timer::Breakable was because a standard Timer is vowed and can't be broken. And I wanted to be able to set a timeout on something that I could break.

On the other hand I wrote it a while ago now. I probably should give it a once over now it's got a mention in the advent calendar.

**Comment by raiph** [comment]
> Is this renaming it to `Timer::Callable`?

`Timer::Cancellable`, but at a guess that's what you meant.

> The reason for calling it `Timer::Breakable` was because a standard `Timer` is `vow`ed and can't be broken. And I wanted to be able to set a timeout on something that I could break.

Ah. OK. Sounds like I completely misunderstood the article's footnote, or jjatria misunderstood the package naming rationale you just explained.

I am curious about what happens when there's a need or desire to alias, rename, or deprecate a package, but this clearly isn't the one. Apologies for the noise. :)

**Comment by alabamenhu** [comment]
> > Is this renaming it to `Timer::Callable`?
> 
> `Timer::Cancellable`, but at a guess that's what you meant.
> 
> > The reason for calling it `Timer::Breakable` was because a standard `Timer` is `vow`ed and can't be broken. And I wanted to be able to set a timeout on something that I could break.
> 
> Ah. OK. Sounds like I completely misunderstood the article's footnote, or jjatria misunderstood the package naming rationale you just explained.
> 
> I am curious about what happens when there's a need or desire to alias, rename, or deprecate a package, but this clearly isn't the one. Apologies for the noise. :)

WRT to changing a name, you can `provide` an alias in the `META6.json`.  I've done it once or twice on modules, and since the ecosystem is still fairly young, I'm giving myself a rule of one year for `provide`-ing under the old name, but down the road that might want to go longer.  I'm not sure if there's a way to issue a warning because of it though.
